version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    rebase-strategy: auto
    labels:
      - dependencies
    ignore:
      - dependency-name: tricount-api
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    rebase-strategy: auto
    labels:
      - dependencies
      - ci
