name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels: [breaking]
  minor:
    labels: [enhancement, feat]
  patch:
    labels: [bug, fix, dependencies, chore, ci, docs]
  default: patch
categories:
  - title: '🚀 New features'
    semver-increment: minor
    when:
      labels:
        - enhancement
        - feat
  - title: '🐛 Bug fixes'
    when:
      labels:
        - bug
        - fix
  - title: '🔒 Security'
    when:
      label: security
  - title: '📦 Dependencies'
    when:
      label: dependencies
  - title: '🔧 Maintenance'
    when:
      labels:
        - chore
        - ci
        - refactor
  - title: '📖 Documentation'
    when:
      labels:
        - docs
        - documentation
  - type: pre-exclude
    when:
      label: skip-changelog
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'
template: |
  ## What's changed

  $CHANGES

  ---
  🙏 Thanks to $CONTRIBUTORS for contributing to this release!
exclude-contributors:
  - geertmeersman[bot]
  - dependabot[bot]
  - github-actions[bot]
