services:
  tricount:
    image: geertmeersman/tricount-web:latest
    container_name: tricount-web
    environment:
      - SECRET_KEY=${SECRET_KEY}
    labels:
      landing.icon: "money"
      landing.name: "tricount"
      landing.description: "Tricount expense tracker"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
