services:
  tricount-web:
    image: geertmeersman/tricount-web:latest
    container_name: tricount-web
    environment:
      - SECRET_KEY=${SECRET_KEY}
    labels:
      landing.icon: "money"
      landing.name: "tricount"
      landing.description: "Tricount expense tracker"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"
