services:
  tricount:
    image: geertmeersman/tricount-web:latest
    container_name: tricount
    environment:
      - SECRET_KEY=${SECRET_KEY}
    labels:
      landing.icon: "money"
      landing.name: "tricount"
      landing.description: "Tricount expense tracker"
    volumes:
      - /docker/volumes/tricount/data:/app/data
    restart: unless-stopped
    networks:
      - websites

networks:
  websites:
    external: true
