services:
  tricount-web:
    image: geertmeersman/tricount-web:latest
    container_name: tricount-web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"
