name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Delete draft releases
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Draft release
        uses: release-drafter/release-drafter@v6.1.0
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update VERSION file
        run: echo "${{ steps.release_drafter.outputs.tag_name }}" > VERSION

      - name: Publish release
        uses: release-drafter/release-drafter@v6.1.0
        id: release_published
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true

      - name: Commit VERSION file
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: "chore: bump version to ${{ steps.release_drafter.outputs.tag_name }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.release_drafter.outputs.tag_name }}

      - name: Update Docker Hub description
        continue-on-error: true
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          readme-filepath: ./DOCKER_HUB.md

      - name: Discord notification
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          tag_name: ${{ steps.release_drafter.outputs.tag_name }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "🚀 New release published: https://github.com/${{ github.repository }}/releases/tag/${{ steps.release_drafter.outputs.tag_name }}"
